version: '3.1'

services:
  dev-db:
    build: ./mongodb_rs/
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    networks:
      - nestbackend
    ports:
      - 27017:27017
